import "~/styles/globals.css";
import  { Inter } from 'next/font/google'
import Header from "~/components/Header";
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <TRPCReactProvider>
          <Header/>
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
